services:

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    volumes:
      - ../..:/workspaces:cached
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.whoami.rule=Host(`whoami.webentor.com`)"
    #   - "traefik.http.routers.whoami.entrypoints=websecure"
    #   - "traefik.http.routers.whoami.tls.certresolver=myresolver"

# networks:
#   traefik:
#     external: true
